name: Metrics

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

concurrency:
  group: metrics-renders
  cancel-in-progress: false

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.isocalendar.svg
          committer_branch: metrics-renders
          committer_message: "chore(metrics): update isometric calendar"
          user: giulio-arecco
          template: classic
          base: ""
          config_timezone: Europe/Rome
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          retries: 3
          retries_delay: 20
          retries_output_action: 3
          retries_delay_output_action: 15

      - name: Languages Activity
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.languages.svg
          committer_branch: metrics-renders
          committer_message: "chore(metrics): update languages activity"
          user: giulio-arecco
          template: classic
          base: ""
          config_timezone: Europe/Rome
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 6
          plugin_languages_other: yes
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          retries: 3
          retries_delay: 20
          retries_output_action: 3
          retries_delay_output_action: 15

      - name: Lines of Code
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.lines.svg
          committer_branch: metrics-renders
          committer_message: "chore(metrics): update lines of code"
          user: giulio-arecco
          template: classic
          base: ""
          config_timezone: Europe/Rome
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: repository
          retries: 3
          retries_delay: 20
          retries_output_action: 3
          retries_delay_output_action: 15
